//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpEntityDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Invoice = new HashSet<Invoice>();
        }
    
        public int BookingID { get; set; }
        public int RoomIDFK { get; set; }
        public Nullable<System.DateTime> BookingFrom { get; set; }
        public Nullable<System.DateTime> BookingTo { get; set; }
        public Nullable<System.DateTime> CheckinTime { get; set; }
        public Nullable<System.DateTime> CheckoutTime { get; set; }
        public Nullable<int> MiniBar { get; set; }
        public Nullable<int> RoomCharge { get; set; }
        public int GuestIDFK { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Guest Guest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
    }
}
