//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpEntityDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public int GuestIDFK { get; set; }
        public Nullable<int> BookingIDFK { get; set; }
        public int InvoiceTotal { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Booking Booking { get; set; }
    }
}
